import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function Page() {
    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 shadow-sm rounded-lg border border-gray-100">
                <div className="mb-8">
                    <Button variant="ghost" asChild className="mb-4 -ml-4 hover:bg-gray-100/50">
                        <Link href="/register" className="flex items-center text-muted-foreground hover:text-foreground">
                            <ArrowLeft className="mr-2 h-4 w-4" />
                            Volver al registro
                        </Link>
                    </Button>
                    <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 mb-2 border-b pb-4">{ `Términos y Condiciones de Uso` }</h1>
                </div>
                <div className="prose prose-blue max-w-none">
                    <p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Términos y condiciones de uso –` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `prodemax` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Última actualización: 18/04/2026` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Bienvenido/a a ProdeMax. Los presentes Términos y Condiciones de Uso (los “Términos”)` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `regulan el acceso, navegación y uso del sitio www.prodemax.com.ar, de todos sus` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `subdominios presentes y futuros, de la plataforma ProdeMax, de sus funcionalidades,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `contenidos, servicios, interfaces, paneles de administración, micrositios corporativos,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `integraciones, módulos y herramientas asociadas (en conjunto, la “Plataforma”).` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Al acceder, registrarse, navegar o utilizar la Plataforma, la persona usuaria declara haber` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `leído, comprendido y aceptado estos Términos. Si no está de acuerdo, deberá abstenerse` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `de utilizarla.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `1. objeto de la plataforma` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax es una solución tecnológica que permite a empresas, organizaciones o clientes` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `corporativos (la “Empresa Cliente”) contar con un entorno digital propio, incluyendo` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `eventualmente un subdominio personalizado y brandeado, para organizar dinámicas` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `internas o comerciales de pronósticos, predicciones, competencias o “prodes” vinculados a` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `eventos y competencias deportivas.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Plataforma permite, entre otras funcionalidades, que la Empresa Cliente:` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `a) administre usuarios participantes;` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `b) cree uno o más prodes;` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `c) configure reglas internas de participación;` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `d) determine premios, beneficios, incentivos o reconocimientos;` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `e) gestione accesos, branding, contenidos y comunicaciones dentro del entorno contratado.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `2. alcance territorial y subdominios` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Estos Términos aplican tanto a prodemax.com.ar como a todo subdominio, micrositio,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `landing, entorno white-label o instancia derivada que ProdeMax cree, habilite,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `administre o licencie para una Empresa Cliente, empleados, colaboradores, clientes o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `terceros autorizados.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Cada subdominio podrá incluir nombre, marca, logo, colores, piezas visuales, textos o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `configuraciones provistas por la Empresa Cliente, sin que ello implique que ProdeMax` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `asuma titularidad, autoría, veracidad, legalidad ni responsabilidad sobre esos contenidos.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `3. modalidad del servicio` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax actúa como proveedor de tecnología, infraestructura, interfaz, soporte y` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `herramientas de gestión.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Salvo pacto escrito en contrario:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no organiza, no patrocina y no financia los premios;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no define unilateralmente las reglas particulares de cada prode creado` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `por una Empresa Cliente;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no garantiza resultados, participación mínima, engagement,` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `conversiones, rendimiento comercial ni satisfacción de los participantes;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no reemplaza asesoramiento legal, fiscal, laboral, comercial ni regulatorio` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `de la Empresa Cliente.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `4. registro y acceso` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Para utilizar ciertas funcionalidades, podrá requerirse registro, alta por invitación, validación` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `interna o asignación de credenciales por parte de la Empresa Cliente o por ProdeMax.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La persona usuaria se obliga a:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `brindar información veraz, exacta y actualizada;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `mantener la confidencialidad de sus credenciales;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `no compartir accesos con terceros no autorizados;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `notificar de inmediato cualquier uso no autorizado, sospecha de intrusión o incidente` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `de seguridad.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente será responsable por los accesos que solicite crear, administrar, dar de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `baja o mantener activos dentro de su entorno.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `5. capacidad y uso autorizado` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Solo podrán usar la Plataforma personas con capacidad legal suficiente para contratar o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `participar conforme a la normativa aplicable y a las políticas internas de la Empresa Cliente.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Si la Empresa Cliente habilitara acceso a menores de edad o a personas con capacidad` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `restringida, será su exclusiva responsabilidad obtener las autorizaciones, consentimientos y` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `resguardos legales correspondientes.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `6. premios, incentivos y responsabilidades de la` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `empresa cliente` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Cada Empresa Cliente será la única y exclusiva responsable de:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `definir las reglas particulares de sus prodes;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `determinar elegibilidad, participación, condiciones de empate o desempate;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ofrecer, comunicar, entregar, pagar y/o gestionar premios, incentivos,` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `reconocimientos o beneficios;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `cumplir con toda obligación legal, impositiva, fiscal, laboral, societaria, reglamentaria` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `o sectorial vinculada con esos premios o dinámicas promocionales;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `redactar, aprobar y publicar, cuando corresponda, sus propias bases particulares,` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `anexos o condiciones complementarias.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no será responsable, en ningún caso, por:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `inexistencia, retraso, defecto, sustitución o falta de entrega de premios;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `reclamos de participantes contra la Empresa Cliente;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `conflictos sobre adjudicación, elegibilidad, empates, anulaciones o interpretación de` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `reglas internas;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `legalidad específica de promociones, concursos, incentivos o beneficios` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `implementados por la Empresa Cliente.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `7. naturaleza del servicio` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Plataforma constituye una herramienta tecnológica de gestión y participación digital.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Salvo indicación expresa, escrita y firmada por ProdeMax, no debe interpretarse como` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `una plataforma de apuestas, juego de azar, asesoramiento financiero, asesoramiento` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `deportivo ni garantía de obtención de premios.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Cada Empresa Cliente asume la responsabilidad de analizar, con asesoramiento propio, si` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `el uso que pretende dar a la Plataforma cumple con la normativa que le resulte aplicable` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `según su actividad, jurisdicción, tipo de participantes y modalidad de premios.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `8. contenidos y materiales cargados por clientes o` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `usuarios` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente y/o los usuarios podrán cargar nombres, logos, textos, imágenes,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `reglas, consignas, listados, configuraciones, comunicaciones y demás materiales.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Queda prohibido cargar contenidos que:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `sean falsos, engañosos, ilícitos o difamatorios;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `infrinjan derechos de terceros;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `contengan malware, código malicioso o elementos destinados a afectar la` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Plataforma;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `vulneren privacidad, confidencialidad o datos personales sin autorización;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `resulten discriminatorios, abusivos, violentos o contrarios al orden público.` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá, sin obligación de previo aviso, suspender, restringir, bloquear, editar,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `despublicar o eliminar contenidos o accesos cuando detecte riesgos técnicos, legales,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `reputacionales o de seguridad.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `9. propiedad intelectual` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Todos los derechos sobre la Plataforma, su software, código, estructura, funcionalidades,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `bases de diseño, interfaces, desarrollos, documentación, procesos, metodologías,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `compilaciones, bases de datos propias, signos distintivos, know-how y materiales del` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Prestador pertenecen a ProdeMax o a sus licenciantes, y se encuentran protegidos por la` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `normativa aplicable.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La contratación del servicio no implica cesión de propiedad intelectual, sino una licencia` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `limitada, revocable, no exclusiva, no transferible y no sublicenciable para usar la Plataforma` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `conforme a estos Términos y a la propuesta comercial contratada.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente conserva la titularidad sobre sus marcas, logos y contenidos propios,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `otorgando a ProdeMax una autorización suficiente para usarlos dentro de la prestación del` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `servicio.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `10. restricciones de uso` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Queda expresamente prohibido:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `copiar, replicar, vender, revender, sublicenciar o explotar comercialmente la` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Plataforma sin autorización;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `descompilar, hacer ingeniería inversa, intentar acceder al código fuente o eludir` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `medidas técnicas de protección;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `realizar scraping, crawling, minería masiva de datos o extracción automatizada no` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `autorizada;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `vulnerar la seguridad, disponibilidad o integridad del sistema;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `usar la Plataforma para fines ilícitos, fraudulentos o no autorizados.` }</li>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `11. disponibilidad y soporte` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax procurará una disponibilidad razonable de la Plataforma, pero no garantiza` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `servicio ininterrumpido, libre de errores o permanente.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Plataforma puede experimentar interrupciones, demoras, pérdidas parciales de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `funcionalidad, mantenimientos programados o incidentes derivados de:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `actualizaciones;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `fallas de hosting, CDN, servidores, APIs, dominios, proveedores cloud o servicios de` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `terceros;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `problemas de conectividad, energía, ciberseguridad o fuerza mayor;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `cambios en calendarios, datos o fuentes deportivas externas.` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá modificar, actualizar, reemplazar o discontinuar funcionalidades en` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `cualquier momento, con o sin aviso previo, cuando ello resulte técnica, comercial o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `legalmente necesario.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `12. integraciones y terceros` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Plataforma puede depender, conectarse o interoperar con servicios de terceros,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `incluyendo pero no limitándose a hosting, pasarelas, proveedores de correo, analítica,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `herramientas de mensajería, validaciones, dominios, APIs, widgets, feeds deportivos o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `servicios de infraestructura.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no será responsable por caídas, errores, cambios de políticas,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `discontinuidades, bloqueos, pérdidas de información, demoras o actos u omisiones de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `terceros.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `13. exactitud de resultados y eventos deportivos` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Los calendarios, resultados, estadísticas, clasificaciones, fixtures, datos deportivos y demás` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `información asociada pueden provenir de fuentes propias o de terceros y podrían contener` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `errores, demoras, cambios, suspensiones, cancelaciones o rectificaciones.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no garantiza exactitud absoluta, actualización en tiempo real ni ausencia de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `discrepancias, y se reserva el derecho de corregir datos, reconfigurar resultados o ajustar` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `cómputos cuando sea necesario.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `14. protección de datos y confidencialidad` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `El uso de la Plataforma se encuentra sujeto también a la Política de Privacidad de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente declara que cuenta con base legal suficiente para cargar o permitir` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `cargar datos personales en la Plataforma, y se compromete a informar a sus usuarios,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `empleados, clientes o participantes sobre el tratamiento de sus datos cuando corresponda.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá actuar, según el caso, como responsable o como encargado/proveedor de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `tratamiento respecto de determinados datos, exclusivamente en el marco de la prestación` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `contratada.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `15. seguridad` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax adoptará medidas técnicas y organizativas razonables de seguridad, pero no` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `garantiza invulnerabilidad absoluta.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente y los usuarios reconocen que ningún entorno digital está exento de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `incidentes, accesos indebidos, ataques, errores humanos o fallos tecnológicos, por lo que` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `aceptan utilizar la Plataforma bajo su propio riesgo razonable.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `16. indemnidad` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La Empresa Cliente se obliga a mantener indemne a ProdeMax, sus titulares, directivos,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `empleados, desarrolladores, proveedores y vinculados, frente a cualquier reclamo,` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `demanda, denuncia, sanción, multa, daño, costo o gasto —incluyendo honorarios` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `profesionales— derivado de:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `reglas o premios definidos por la Empresa Cliente;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `incumplimientos regulatorios, laborales, fiscales o promocionales de la Empresa` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Cliente;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `uso indebido de la Plataforma;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `contenidos aportados por la Empresa Cliente o sus usuarios;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `violación de derechos de terceros;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `datos cargados sin base legal suficiente.` }</li>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `17. limitación de responsabilidad` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `En la máxima medida permitida por la ley aplicable:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no responderá por daños indirectos, lucro cesante, pérdida de chance,` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `pérdida de negocio, pérdida reputacional, pérdida de datos, interrupción operativa ni` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `daños punitivos;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `la responsabilidad total acumulada de ProdeMax, de existir, quedará limitada al` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `monto efectivamente abonado por la Empresa Cliente a ProdeMax por el servicio en` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `los tres (3) meses anteriores al hecho que originó el reclamo;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax no será responsable frente a usuarios finales por obligaciones que` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `correspondan a la Empresa Cliente.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `18. suspensión y baja` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá suspender o cancelar accesos, subdominios, cuentas o servicios cuando:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `exista mora en el pago;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `se detecte uso ilícito o riesgoso;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `haya orden administrativa o judicial;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `la continuidad del servicio genere un riesgo técnico, legal o reputacional;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `la Empresa Cliente incumpla estos Términos o la propuesta comercial.` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `La baja del servicio no extingue obligaciones pendientes ni libera a la Empresa Cliente de` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `sus responsabilidades previas frente a participantes o terceros.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `19. vigencia de subdominios y branding` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Los subdominios, diseños, customizaciones o entornos white-label estarán vigentes` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `mientras dure la relación comercial y mientras la Empresa Cliente se encuentre al día con` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `sus obligaciones.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Salvo acuerdo escrito en contrario:` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax conserva control técnico sobre la infraestructura del subdominio;` }</li>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `la Empresa Cliente no adquiere derecho de propiedad sobre la arquitectura, software` }</li>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `base ni desarrollos generales;` }</p>
<li className="ml-4 mb-2 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá dar de baja el subdominio al finalizar la relación comercial.` }</li>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `20. modificaciones` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `ProdeMax podrá modificar estos Términos en cualquier momento. La versión vigente será la` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `publicada en la Plataforma. La continuidad en el uso luego de su actualización implicará` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `aceptación de los nuevos términos.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `21. nulidad parcial` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Si alguna cláusula fuera declarada inválida o inaplicable, ello no afectará la validez del resto` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `del documento.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `22. ley aplicable y jurisdicción` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Estos Términos se regirán por las leyes de la República Argentina.` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Toda controversia será sometida a la jurisdicción de los tribunales ordinarios con` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `competencia en la Ciudad Autónoma de Buenos Aires (CABA), con renuncia a cualquier otro fuero o` }</p>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `jurisdicción, salvo que una norma imperativa disponga lo contrario.` }</p>
<h2 className="text-xl font-bold mt-6 mb-2 text-primary">{ `23. contacto` }</h2>
<p className="mb-4 text-gray-700 leading-relaxed text-sm md:text-base">{ `Para consultas legales, técnicas o vinculadas con estos Términos: info@prodemax.com.ar.` }</p>
                </div>
            </div>
        </div>
    );
}